unstable_features = true
edition = "2024"

reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

merge_derives = true
reorder_impl_items = true

comment_width = 120
format_code_in_doc_comments = true
max_width = 80
wrap_comments = true
