version = "1"

[package.curl]
display = "cURL"
packages.apt = "curl"
packages.brew = "curl"
detect = "curl --version"

[package.git]
display = "Git"
packages.apt = "git"
packages.brew = "git"
detect = "git --version"

[package.unzip]
display = "Unzip"
packages.apt = "unzip"
packages.brew = "unzip"
detect = "unzip --version"

[package.brew]
display = "Homebrew"
packages.custom = "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
detect = "brew --version"
dependencies = ["curl"]
